#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/www.rooq.tech.pem
        redirect scheme https if !{ ssl_fc }
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 357794-web-01 54.157.165.199:80 check
        server 357794-web-02 54.237.14.178:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
